/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-23 15:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class companyDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>회사 수정</title>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<meta name=\"description\" content=\"\">\r\n");
      out.write("	<meta name=\"author\" content=\"\">\r\n");
      out.write("	<meta name=\"robots\" content=\"noindex\">	\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/bootstrap.css?1630317764\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/jquery-ui.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/ii.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/db-icons.css?1577682282\"> <!-- 아이콘 필수 -->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/material-design-iconic-font.min.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/bootstrap-datepicker.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/black-tie.css?1608189400\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/simple-line-icons.css?1608179394\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/fonts/im-icon/style.css?1656383913\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/fonts/froala-emoji-tap/style.css?1660095148\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/preloader.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/owl.carousel2.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/slick.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/animate.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/nprogress.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/trackpad-scroll-emulator.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/font-awesome.min.css?1626931454\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/font-awesome5.min.css?1660780829\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/froala_311/css/froala_editor.pkgd.css?1660095140\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/froala_311/css/froala_style.min.css?1660095060\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/emoji.css?1660095097\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/froala/custom-theme-v3.css?1663833898\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/colorpicker.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/codemirror.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/bootstrap-spinner.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/chosen.css?1617331870\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/fullcalendar.min.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/morris.core.css?1577682282\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/lightgallery.min.css?1596596378\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/im_component.css?1636689958\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/site/admin/admin.css?1590627710\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/site/admin/toastr.css?1593569516\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/site/alarm_menu.css?1648796493\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/fonts/fontello/src/css/fontello.css?1657576838\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/site/admin/bootstrap-theme-dashboard.css?1618365623\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/site/admin/dashboard.css?1663833898\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/site/admin/select2.css?1590627710\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/site/admin/accordion.css?1653367465\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/regularly.css?1658818153\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://vendor-cdn.imweb.me/css/tailwind.css?1664422527\">\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/jquery.js?1627517460\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/jquery.browser.js?1577682292\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/jquery-ui.min.js?1577682292\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/bootstrap.min.js?1630317768\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/floating-ui-core@1.0.1.js?1662343131\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/floating-ui-dom@1.0.1.js?1662343131\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/tinycolor-min.js?1577682292\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/common.js?1661221108\"></script>\r\n");
      out.write("	<script src=\"https://vendor-cdn.imweb.me/js/table_list.js?1633057104\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/admin/companyDetail.css\">\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"menubar-hoverable header-fixed menubar-pin menubar-visible\">\r\n");
      out.write("	<!-- START BASE -->\r\n");
      out.write("    <div id=\"base\"> \r\n");
      out.write("		<!-- START HEADER -->\r\n");
      out.write("		<header class=\"top_header\" id=\"default_header\"> \r\n");
      out.write("			<div class=\"headerbar\">\r\n");
      out.write("				<div class=\"headerbar-left\">\r\n");
      out.write("					<ul class=\"header-nav header-nav-options\">\r\n");
      out.write("						<li class=\"hidden-lg hidden-md\">\r\n");
      out.write("							<a class=\"btn btn-icon-toggle menubar-toggle\" data-toggle=\"menubar\" href=\"javascript:void(0);\">\r\n");
      out.write("								<i class=\"btl bt-bars\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"header-nav-brand\">\r\n");
      out.write("							<div class=\"brand-holder\">\r\n");
      out.write("								<span class=\"location_text\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/companyDetail.jsp\">회사 수정</a>	<!-- 동일 페이지로 재이동 -->\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"headerbar-right\">\r\n");
      out.write("					<ul class=\"header-nav header-nav-options _option_list\">\r\n");
      out.write("						<li>\r\n");
      out.write("							<button type = \"button\" class=\"btn btn-primary hidden-xs\"  onclick = \"send()\" >저장</button>\r\n");
      out.write("							<a class=\"btn btn-bright hidden-sm hidden-md hidden-lg\" style=\"padding: 4px 6px;\" onclick=\"location.href='#'\"><i class=\"btl bt-plus vertical-middle\"></i></a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul><!--end .header-nav-options -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header> <!-- END HEADER -->\r\n");
      out.write("\r\n");
      out.write("		<!-- START MENUBAR HEADER -->\r\n");
      out.write("		<div class=\"fold_area tabled animate\"> \r\n");
      out.write("			<div class=\"table-cell vertical-middle\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/adminIndex.jsp\" class=\"logo_icon_menu\"> <!-- 관리자 메인 메뉴로 이동 -->\r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/white_cosmos.png\"> <!-- 좌측 상단 로고 -->\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div> <!-- END MENUBAR HEADER -->\r\n");
      out.write("\r\n");
      out.write("		<!-- BEGIN MENUBAR-->\r\n");
      out.write("		<div id=\"menubar\" class=\"animate\">\r\n");
      out.write("			<div class=\"menubarContent\" tabindex=\"0\">\r\n");
      out.write("				<div class=\"menubar-scroll-panel\">\r\n");
      out.write("					<div class=\"tabled full-width\">\r\n");
      out.write("						<div class=\"adminLogo\">\r\n");
      out.write("							<img src=\"https://testchoo.imweb.me/common/img/flag_shapes/flag_kr_circle.png\" width=\"20\" height=\"20\"> <!-- 사진 변경 필요 -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"brand-holder\">\r\n");
      out.write("							<span class=\"title\">COSMOS</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("					<ul id=\"main-menu\" class=\"gui-controls\">\r\n");
      out.write("						<li class=\"  \" data-title=\"preview\">\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/main/index.jsp\" target=\"_blank\"> <!-- 우리 cosmos 홈페이지 url 교체 필요 -->\r\n");
      out.write("								<div class=\"gui-icon\">\r\n");
      out.write("									<i class=\"db-preview\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"title\">사이트 바로가기</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"spacer\"></li> <!-- 공간 여백 div -->\r\n");
      out.write("\r\n");
      out.write("						<li class=\"  \" data-title=\"adminPage\">\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/adminIndex.jsp\"> <!-- 관리자 메인 화면 링크-->\r\n");
      out.write("								<div class=\"gui-icon\">\r\n");
      out.write("									<i class=\"db-dashboard\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"title\">관리자 홈</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"active gui-folder expanded\" data-title=\"member\"> <!-- 현재 이동한 페이지의 카테고리를 활성화 시켜줘야함 -->\r\n");
      out.write("							<a href=\"#\" class=\"sidebar-nav-menu\" onclick=\"return false;\">\r\n");
      out.write("								<div class=\"gui-icon\">\r\n");
      out.write("									<i class=\"db-user\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"title\">사용자/회사 관리</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"  \" data-title=\"memberList\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/memberListOk.ad\">   <!-- 이동할 페이지 url 작성 -->\r\n");
      out.write("										<span class=\"title\">사용자 목록</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"active expanded\" data-title=\"companyList\">  <!-- a태그의 클래스명이 li 태그 클래스에 출가된다. 활성화 된 클래스 표시(active) -->\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/companyListOk.ad\" class=\" active\">  <!-- 해당 페이지의 목록에 active가 들어가야지 음영처리가된다. -->\r\n");
      out.write("										<span class=\"title\">회사 목록</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("							\r\n");
      out.write("						<li class=\"gui-folder\" data-title=\"contents\"> \r\n");
      out.write("							<a href=\"#\" class=\"sidebar-nav-menu1\" onclick=\"return false;\">\r\n");
      out.write("								<div class=\"gui-icon\">\r\n");
      out.write("									<i class=\"db-pencil\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"title\">컨텐츠 관리</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"  \" data-title=\"contentsPost\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/contentListOk.ad\">\r\n");
      out.write("										<span class=\"title\">게시물 관리</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"  \" data-title=\"contentsComment\"> \r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/replyListOk.ad\">\r\n");
      out.write("										<span class=\"title\">댓글 관리</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"  \" data-title=\"contentsInjuiry\"> \r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/InquirySelectOk.ad\"> \r\n");
      out.write("										<span class=\"title\">문의글 관리</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\" \" data-title=\"contentsNotice\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/notice.jsp\">\r\n");
      out.write("										<span class=\"title\">공지사항 관리</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("							\r\n");
      out.write("						<li class=\"gui-folder\" data-title=\"stat\">\r\n");
      out.write("							<a href=\"#\" class=\"sidebar-nav-menu\" onclick=\"return false;\">\r\n");
      out.write("								<div class=\"gui-icon\">\r\n");
      out.write("									<i class=\"db-status-up\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"title\">통계</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"  \" data-title=\"statAnalytics\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/statAnalytics.jsp\">\r\n");
      out.write("										<span class=\"title\">기간별 분석</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"  \" data-title=\"statVisitor\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/statVisitor.jsp\">\r\n");
      out.write("										<span class=\"title\">방문자 통계</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"gui-folder\" data-title=\"config\">\r\n");
      out.write("							<a href=\"#\" class=\"sidebar-nav-menu1\" onclick=\"return false;\">\r\n");
      out.write("								<div class=\"gui-icon\">\r\n");
      out.write("									<i class=\"db-settings\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"title\">환경설정</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"  \" data-title=\"configPopup\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/bannerListOk.ad\">\r\n");
      out.write("										<span class=\"title\">배너 관리</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>		\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div><!-- END MENUBAR-->\r\n");
      out.write("		\r\n");
      out.write("		<!-- START MAIN CONTENT -->\r\n");
      out.write("\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("			<section>\r\n");
      out.write("				<div class=\"card style-transparent card-top no-tab\">\r\n");
      out.write("					<div class=\"card-head\">\r\n");
      out.write("						<header>\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/companyListOk.ad\" onclick=\"window.location = '#';\"> <!-- 회사 목록 리스트 주소 입력 필요 / 이 전 페이지 -->\r\n");
      out.write("								<i class=\"zmdi zmdi-arrow-back\"></i>리스트로 돌아가기\r\n");
      out.write("							</a>\r\n");
      out.write("						</header>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("				<div class=\"section-body\">\r\n");
      out.write("					<div class=\"tab-pane\" id=\"daily\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<div class=\"card\">\r\n");
      out.write("									<div class=\"card-head\">\r\n");
      out.write("										<header>회사 정보</header>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"card-body border-top\">										\r\n");
      out.write("										<div class=\"profile-image text-center margin-bottom-xxl\">\r\n");
      out.write("											<div id=\"fileupload_profile_img\">\r\n");
      out.write("												<img class=\"company\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/company/company.png\" id=\"profile_img\" width=\"72\" height=\"72\" class=\"img-circle\">\r\n");
      out.write("												<div id=\"drop_profile_img\">\r\n");
      out.write("													<input type=\"file\" name=\"files[]\" style=\"width: 100%\" accept=\"image/jpeg, image/jpg, image/png, image/gif, image/svg+xml\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"over\">\r\n");
      out.write("													<i class=\"zmdi zmdi-camera\"></i>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											\r\n");
      out.write("											<h3 class=\"text-15\"></h3>\r\n");
      out.write("										</div><!--end.profile-image-->\r\n");
      out.write("		\r\n");
      out.write("										<div class=\"profile-info\">\r\n");
      out.write("											<form name=\"companyForm\" id=\"dof\" method=\"get\" class=\"form-horizontal form-validate\" enctype=\"multipart/form-data\"  onsubmit=\"return false;\"  >\r\n");
      out.write("												<!-- 해당 회사 상세내용 아래 방법으로 코드 작성  -->\r\n");
      out.write("												<!-- <input type=\"hidden\" name=\"idx\" value=\"22645265\">\r\n");
      out.write("												<input type=\"hidden\" name=\"code\" value=\"m20220929a41c742d48942\">\r\n");
      out.write("												<input type=\"hidden\" name=\"join_type_code\" value=\"t20220929dd5f7889009e5\">\r\n");
      out.write("												<input type=\"hidden\" name=\"photo\" value=\"\">\r\n");
      out.write("												<input type=\"hidden\" name=\"photo_tmp_idx\" value=\"\" id=\"photo_tmp_idx\">\r\n");
      out.write("												<input type=\"hidden\" name=\"from_permission\" value=\"\"> -->\r\n");
      out.write("												<!-- 해당 사용자 상세내용 -->\r\n");
      out.write("												\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<label  class=\"col-sm-3 control-label text-right\" for=\"member_item_m20220929a41c742d48942\">회사명\r\n");
      out.write("														<span class=\"text-danger\"></span>\r\n");
      out.write("													</label>\r\n");
      out.write("													<div class=\"col-md-9\">\r\n");
      out.write("														<input name=\"companyName\"type=\"text\" required=\"required\"  id=\"member_item_m20220929a41c742d48942\" class=\"form-control\" aria-required=\"true\">\r\n");
      out.write("														<div class=\"form-control-line\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("																													\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													\r\n");
      out.write("													<label  class=\"col-sm-3 control-label text-right\" for=\"member_item_m20220929a41c742d48942\">홈페이지</label>\r\n");
      out.write("														<span class=\"text-danger\"></span>\r\n");
      out.write("													<div class=\"col-md-9\">\r\n");
      out.write("														<input name=\"companyUrl\" type=\"text\" required=\"required\"  id=\"member_item_m20220929a41c742d48942\" class=\"form-control\"  aria-required=\"true\">\r\n");
      out.write("														<div class=\"form-control-line\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("		\r\n");
      out.write("												<div class=\"_type_form_wrap\">\r\n");
      out.write("													<div class=\"form-group\">\r\n");
      out.write("														<label class=\"col-sm-3 control-label text-right\" for=\"user_name\">설명\r\n");
      out.write("															<span class=\"text-danger\"></span>\r\n");
      out.write("														</label>\r\n");
      out.write("														<div class=\"col-md-9\">\r\n");
      out.write("															<input  name=\"companyContent\" type=\"text\"  id=\"user_name\" class=\"form-control\" >\r\n");
      out.write("															<div class=\"form-control-line\"></div>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</form>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div><!--end.card-body-->\r\n");
      out.write("								</div><!--end.card-->\r\n");
      out.write("							</div><!--end.col-->\r\n");
      out.write("	\r\n");
      out.write("					\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div> \r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- END MAIN CONTENT -->\r\n");
      out.write("	</div> <!-- END BASE -->\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/admin/companyDetail.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	const pageURI = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
