/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-25 08:13:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.myPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class friend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/gb_0900_csh/jsp/workspace/cosmos-project/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/gb_0900_csh/jsp/workspace/cosmos-project/WebContent/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1665992284967L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>친구관리</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/myPage/friend.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main/dimmed.css\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/cosmosProfile.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"dimmed_233vf\"> \r\n");
      out.write("	<div class=\"dimmed_image_23fds\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search_results\" style=\"margin-top:50px;\">\r\n");
      out.write("         <a onclick=\"send()\" style=\"width:10%\">\r\n");
      out.write("          <svg stroke=\"currentColosr\" fill=\"currentColor\" stroke-width=\"0\"\r\n");
      out.write("        viewBox=\"0 0 448 512\" color=\"808080\" cursor=\"pointer\" height=\"30\" width=\"30\"\r\n");
      out.write("         xmlns=\"http://www.w3.org/2000/svg\" style=\"color: rgb(128, 128, 128);\" >\r\n");
      out.write("          <path\r\n");
      out.write("                    d=\"M 257.5 445.1 l -22.2 22.2 c -9.4 9.4 -24.6 9.4 -33.9 0 L 7 273 c -9.4 -9.4 -9.4 -24.6 0 -33.9 L 201.4 44.7 c 9.4 -9.4 24.6 -9.4 33.9 0 l 22.2 22.2 c 9.5 9.5 9.3 25 -0.4 34.3 L 136.6 216 H 424 c 13.3 0 24 10.7 24 24 v 32 c 0 13.3 -10.7 24 -24 24 H 136.6 l 120.5 114.8 c 9.8 9.3 10 24.8 0.4 34.3 Z\">\r\n");
      out.write("                </path>\r\n");
      out.write("       </svg>\r\n");
      out.write("       </a>\r\n");
      out.write("       \r\n");
      out.write("       <script >\r\n");
      out.write("    	function send(){\r\n");
      out.write("    		$(\".dimmed_233vf\").css(\"display\",\"grid\");\r\n");
      out.write("    		location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/mainBoard.ma\";\r\n");
      out.write("    	}\r\n");
      out.write("    	</script>\r\n");
      out.write("        <div class=\"ui segments\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"ui segment\">\r\n");
      out.write("              <div class=\"friend_header\">\r\n");
      out.write("                <div class=\"extra\">\r\n");
      out.write("                        <div class=\"request-button\" data-url=\"/api/users/324116/request_button\">\r\n");
      out.write("                            <div class=\"ui mini basic buttons friend_btn\" style=\"float: right;\">\r\n");
      out.write("                                <a  class=\"ui basic button friend_btn\" id=\"btn-modal\">친구 추가</a>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <span class=\"desc\">\r\n");
      out.write("                    친구 목록\r\n");
      out.write("                </span>\r\n");
      out.write("                \r\n");
      out.write("            </div> \r\n");
      out.write("    <div class=\"ui segment\">\r\n");
      out.write("        <div class=\"ui items\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ui segment friendInfoList_2f\">\r\n");
      out.write("                \r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--     <div class=\"pagination\" onclick=\"handleClick()\">\r\n");
      out.write("        <a href=\"#\">&laquo;</a>\r\n");
      out.write("        <a class=\"active\" href=\"#\">1</a>\r\n");
      out.write("        <a class=\"num\"href=\"#\">2</a>\r\n");
      out.write("        <a class=\"num\"href=\"#\">3</a>\r\n");
      out.write("        <a class=\"num\"href=\"#\">4</a> \r\n");
      out.write("        <a class=\"num\"href=\"#\">5</a>\r\n");
      out.write("        <a href=\"#\">&raquo;</a>\r\n");
      out.write("      </div>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal\" id=\"modal\">\r\n");
      out.write("        <div class=\"black_bg\"></div>\r\n");
      out.write("        <div class=\"modalW\">\r\n");
      out.write("            <div class=\"modal_first\">\r\n");
      out.write("                <div class=\"loginModal_modalHeader\">\r\n");
      out.write("                    <img class=\"loginModal_logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/logo.png\" alt=\"welcome\">\r\n");
      out.write("                    <div class=\"loginModal_exitWrapper\">\r\n");
      out.write("                        <svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" tabindex=\"1\"\r\n");
      out.write("                            height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                            <path\r\n");
      out.write("                                d=\"M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z\">\r\n");
      out.write("                            </path>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"loginModal_modalContent second hidden\">\r\n");
      out.write("                    <img class=\"topBar_backButton__3HlkH\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/arrow-left.png\" alt=\"back-button\" id=\"close-btn\">\r\n");
      out.write("                    <h1 class=\"setNickname_title__xgVq4\">친구 추가를 하시려면<br>친구의 닉네임을 입력해주세요</h1>\r\n");
      out.write("                    <div class=\"setNickname_inputWrapper__2SFvb\">\r\n");
      out.write("                        <h3>친구 이름</h3>\r\n");
      out.write("                        <input class=\"setNickname_nicknameInput__1J1el\" type=\"text\" name=\"nickNameInput\" value=\"\"\r\n");
      out.write("                            autocomplete=\"off\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type = \"button\" class=\"setNickname_buttonNext__2pE6g\" name=\"complete\" onclick=\"duplicatedNickname()\">추가하기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	const page_urI_2f = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/myPage/friend.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
