/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-25 08:12:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.fix;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_005fnotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/gb_0900_csh/jsp/workspace/cosmos-project/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/gb_0900_csh/jsp/workspace/cosmos-project/WebContent/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1665992284967L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main/header_notice.css\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"header\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/mainBoard.ma\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/logo.png\" alt=\"logo\" class=\"logo\">\r\n");
      out.write("            \r\n");
      out.write("        </a>\r\n");
      out.write("        <div>\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/mainSearchOk.ma\" name=\"searchForm\" method=\"get\" enctype=\"multipart/form-data\" class=\"header_search\">\r\n");
      out.write("               <input type=\"text\" name=\"header_search_input\" placeholder=\"회사나 제목을 입력해주세요...\">\r\n");
      out.write("               <button type=\"button\" class=\"header_search_button\" onclick=\"searchSend()\">검색</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar\">\r\n");
      out.write("            <button class=\"navbar_post\">새 글 쓰기</button>\r\n");
      out.write("            <div class=\"notice\">\r\n");
      out.write("                <div class=\"notice_wrapper\">\r\n");
      out.write("                <div class=\"notice_alarmNoticer__18fSt\"></div>\r\n");
      out.write("                    <img src=\"https://holaworld.io/images/info/notification.svg\" alt=\"notification\" class=\"notice\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"loginUser\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/cosmosProfile.png\" alt=\"userImg\" class=\"loginUser\">\r\n");
      out.write("                <svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                    <path d=\"M7 10l5 5 5-5z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("                 <div class=\"dropdownBar_menuWrapper_header loginHeaderUnVisibie\">\r\n");
      out.write("                    <ul class=\"dropdownBar_menu_list\">\r\n");
      out.write("                    	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        <li class=\"dropdownBar_menuItem_header\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/FriendInfoList.us\" style=\"display: inline-block;\"> 친구 목록</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdownBar_menuItem_header dropdownBar_newPost_header\">\r\n");
      out.write("                            <a href=\"#\" style=\"display: inline-block;\">새 글 작성</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    \r\n");
      out.write("                        <li class=\"dropdownBar_menuItem_header\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/mainSearch.ma?\" style=\"display: inline-block;\">내 작성글</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdownBar_menuItem_header\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/userInfo.us\" style=\"display: inline-block;\">내 정보</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdownBar_menuItem_header\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/logout.us\" style=\"display: inline-block;\">로그아웃</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- 생성 -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"noticeDropdownBar_noticeWrapper loginHeaderUnVisibie\">\r\n");
      out.write("        <div class=\"noticeDropdownBar_noticeHeader\"> \r\n");
      out.write("             <span>읽지 않은 알림 (<span class=\"noticeCount\">0</span>) </span>\r\n");
      out.write("            <div class=\"noticeDropdownBar_exitWrapper\">\r\n");
      out.write("                <svg class = \"notification\" stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" tabindex=\"1\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                    <path d=\"M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"\" >\r\n");
      out.write("        <div class=\"noticeDropdownBar_empty\" onclick=\"alarmSend()\">서비스 준비 중입니다 </a> \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        	<!-- 문의 답변  -->\r\n");
      out.write("        <ul class=\"noticeDropdownBar_noticeBody__240wL\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("        \r\n");
      out.write("        	<!-- 프로젝트 게시판   -->\r\n");
      out.write("           <ul class=\"noticeBoardReply\">\r\n");
      out.write("         ");
      out.write(" \r\n");
      out.write("               </ul>\r\n");
      out.write("			<!-- 프로젝트 공지사항  -->\r\n");
      out.write("           <ul class=\"projectnotice\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("\r\n");
      out.write("			<!-- 프로잭트 모집   -->\r\n");
      out.write("           <ul class=\"projectReply\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("\r\n");
      out.write("			<!-- 스터디 모집함  -->\r\n");
      out.write("           <ul class=\"projectStudyReply\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<!-- 프로젝트 (컴퍼니) 모집함  -->\r\n");
      out.write("           <ul class=\"projectCompanyReply\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- 스터디 (컴퍼니) 모집함  -->\r\n");
      out.write("           <ul class=\"studyCompanyReply\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- 관리자의 전체 공지사항   -->\r\n");
      out.write("           <ul class=\"adminNotice\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    $loginSvg = $(\"div.loginUser\");\r\n");
      out.write("\r\n");
      out.write("    $dropdownBar_menuWrapper_header = $(\".dropdownBar_menuWrapper_header\");\r\n");
      out.write("    loginSvgCheck = -1;\r\n");
      out.write("\r\n");
      out.write("    $loginSvg.click(function () {\r\n");
      out.write("        loginSvgCheck *= -1;\r\n");
      out.write("        if (loginSvgCheck > 0) {\r\n");
      out.write("            $dropdownBar_menuWrapper_header.removeClass(\"loginHeaderUnVisibie\").addClass(\"loginHeaderVisibie\")\r\n");
      out.write("        } else {\r\n");
      out.write("            $dropdownBar_menuWrapper_header.removeClass(\"loginHeaderVisibie\").addClass(\"loginHeaderUnVisibie\")\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $noticeSvg = $(\"div.notice_wrapper\");\r\n");
      out.write("\r\n");
      out.write("    $noticeWrapper = $(\".noticeDropdownBar_noticeWrapper\");\r\n");
      out.write("    noticeSvgCheck = -1;\r\n");
      out.write("	\r\n");
      out.write("    $noticeSvg.click(function () {\r\n");
      out.write("    	noticeSvgCheck *= -1;\r\n");
      out.write("        if (noticeSvgCheck > 0) {\r\n");
      out.write("            $noticeWrapper.removeClass(\"loginHeaderUnVisibie\").addClass(\"loginHeaderVisibie\")\r\n");
      out.write("        } else {\r\n");
      out.write("            $noticeWrapper.removeClass(\"loginHeaderVisibie\").addClass(\"loginHeaderUnVisibie\")\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    $exit = $(\"div.noticeDropdownBar_exitWrapper\");\r\n");
      out.write("    exitCheck = -1;\r\n");
      out.write("	\r\n");
      out.write("    $exit.click(function () {\r\n");
      out.write("    	$(this).closest($noticeWrapper).removeClass(\"loginHeaderVisibie\").addClass(\"loginHeaderUnVisibie\");\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    $post = $(\".navbar_post\");\r\n");
      out.write("    \r\n");
      out.write("    $post.click(function(){\r\n");
      out.write("    	/*  $(\".dimmed_233vf\").css(\"display\",\"grid\"); */\r\n");
      out.write("    	$(location).attr(\"href\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/write.bo\");\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    /* 읽지않은 알림 카운트 */\r\n");
      out.write("    \r\n");
      out.write("  /*   countOk();\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function countOk() {\r\n");
      out.write("    	$.ajax({\r\n");
      out.write("			url: \"/main/alarmListOk.ma\",\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("			success: countShowOk\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("	}\r\n");
      out.write("    \r\n");
      out.write("    		function countShowOk(count) {\r\n");
      out.write("    			\r\n");
      out.write("    			console.log(\"ajax 들어옴  카운트\")\r\n");
      out.write("    			console.log(count)\r\n");
      out.write("    			let text=\"\";\r\n");
      out.write("		\r\n");
      out.write("    			\r\n");
      out.write("    			text+=`<div class=\"noticeDropdownBar_noticeHeader\">`\r\n");
      out.write("	   			text+=` +<span>읽지 않은 알림 (<span class=\"noticeCount\">\"count\"</span>) </span>+`\r\n");
      out.write("    			text+=`<div class=\"noticeDropdownBar_exitWrapper\">`\r\n");
      out.write("    			text+=`<svg class = \"notification\" stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" tabindex=\"1\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\">`\r\n");
      out.write("    			text+=`<path d=\"M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z\"></path>`\r\n");
      out.write("    			text+=`</svg>`\r\n");
      out.write("    			text+=`</div>`\r\n");
      out.write("    			text+=`</div>`\r\n");
      out.write("    			text+=`<div class=\"noticeDropdownBar_empty\">알림함이 비어있습니다</div>`\r\n");
      out.write("    			\r\n");
      out.write("    		  $(\".noticeDropdownBar_noticeWrapper loginHeaderUnVisibie\").html(text);\r\n");
      out.write("    			\r\n");
      out.write("    			\r\n");
      out.write("			} */\r\n");
      out.write("    		\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    	\r\n");
      out.write("  /*   /* 문의하기 답변 완료   */\r\n");
      out.write("   /*   listOk();  */\r\n");
      out.write("    		\r\n");
      out.write("  /* 	function listOk() {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"/main/alarmListOk.ma\",\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("			success: showAlarmListOk\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("    			\r\n");
      out.write("	}\r\n");
      out.write("    		/* 문의하기 답변 완료   */\r\n");
      out.write("    		/* function showAlarmListOk(result) {\r\n");
      out.write("    			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("    			  let text=\"\";\r\n");
      out.write("    			  var count=0;	\r\n");
      out.write("    			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("    			  	alert(\"데이터 보내기 성공\")\r\n");
      out.write("    				  console.log(result.alarmList)\r\n");
      out.write("    				  count++;\r\n");
      out.write("    			\r\n");
      out.write("    			  	 text+=`<div class=\"noticeDropdownBar_noticeHeader\">`\r\n");
      out.write("    		   		 text+=` <span>읽지 않은 알림 (<span class=\"noticeCount\">`+count+`</span>) </span>`\r\n");
      out.write("    	    		 text+=`<div class=\"noticeDropdownBar_exitWrapper\">`\r\n");
      out.write("    	    		 text+=`<svg class = \"notification\" stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" tabindex=\"1\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\">`\r\n");
      out.write("    	    		 text+=`<path d=\"M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z\"></path>`\r\n");
      out.write("    	    		 text+=`</svg>`\r\n");
      out.write("    	    		 text+=`</div>`\r\n");
      out.write("    	    		 text+=`</div>`\r\n");
      out.write("    	    		 text+=`<div class=\"noticeDropdownBar_empty\">알림함이 비어있습니다</div>`\r\n");
      out.write("    				 text+= `<li class=\"noticeDropdownBar_noticeTitleWrapper__6ye2L false\">`;                         \r\n");
      out.write("    				 text+=`<a class=\"noticeDropdownBar_noticeLink__mBRje\"`+`href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/inquiry/inquiryBoard.jsp\" >`;	\r\n");
      out.write("    				 text+=`<span class=\"noticeListOn\">문의 답변이 달렸습니다</span>`;\r\n");
      out.write("    				 text+=`</a>`;	\r\n");
      out.write("    				 text+=`</li>`;\r\n");
      out.write("    				 text+=`<br>`;\r\n");
      out.write("    				 text+= `<li class=\"noticeBoardList\">`;                         \r\n");
      out.write("      				 text+=` <a class=\"noticeMoveProjectLib\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/myPage/my_project_lib.jsp\" >`;	\r\n");
      out.write("      				 text+=`<span class=\"noticeProjectLib\">프로젝트 게시판이 올라왔습니다</span>`;\r\n");
      out.write("      				 text+=`</a>`;	\r\n");
      out.write("      				 text+=`</li>`;	\r\n");
      out.write("      				 text+=`<br>`;\r\n");
      out.write("      				 text+= `<li class=\"projectNotice\">`;                         \r\n");
      out.write("     				 text+=` <a class=\"moveNoticeProject\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/myPage/my_project_notice.jsp\" >`;	\r\n");
      out.write("     				 text+=`<span class=\"noticeProject\">프로젝트 공지사항이 올라왔습니다</span>`;\r\n");
      out.write("     				 text+=`</a>`;	\r\n");
      out.write("     				 text+=`</li>`;\r\n");
      out.write("     				 text+=`<br>`;\r\n");
      out.write("     				 text+= `<li class=\"projectReplyNotice\">`;                         \r\n");
      out.write("      				 text+=` <a class=\"moveBoardProject\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardProject.jsp\" >`;	\r\n");
      out.write("      				 text+=`<span class=\"noticeReplyProject\">(프로젝트) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("      				 text+=`</a>`;	\r\n");
      out.write("      				 text+=`</li>`;\r\n");
      out.write("      				 text+=`<br>`;\r\n");
      out.write("      				 text+= `<li class=\"studyReplyNotice\">`;                         \r\n");
      out.write("      				 text+=` <a class=\"moveBoardStudy\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardStudy.jsp\" >`;	\r\n");
      out.write("      				 text+=`<span class=\"noticeReplyStudy\">(스터디) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("      				 text+=`</a>`;	\r\n");
      out.write("      				 text+=`</li>`;\r\n");
      out.write("      				 text+=`<br>`;\r\n");
      out.write("      				 text+= `<li class=\"projectCompanyReplyNotice\">`;                         \r\n");
      out.write("     				 text+=`<a class=\"moveBoardProjectCompany\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardProject_company.jsp\" >`;	\r\n");
      out.write("     				 text+=`<span class=\"noticeReplyProjectCompany\">(프로젝트 회사) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("     				 text+=`</a>`;	\r\n");
      out.write("     				 text+=`</li>`;\r\n");
      out.write("     				 text+=`<br>`;\r\n");
      out.write("     				 text+= `<li class=\"studyCompanyReplyNotice\">`;                         \r\n");
      out.write("      				 text+=`<a class=\"moveBoardStudyCompany\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardStudy_company.jsp\" >`;	\r\n");
      out.write("      				 text+=`<span class=\"noticeReplyStudyCompany\">(스터디 회사) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("      				 text+=`</a>`;	\r\n");
      out.write("      				 text+=`</li>`;\r\n");
      out.write("      				 text+=`<br>`;\r\n");
      out.write("      				 text+= `<li class=\"adminNotice1\">`;                         \r\n");
      out.write("      				 text+=`<a class=\"moveAdminNotice\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/allNotice.jsp\" >`;	\r\n");
      out.write("      				 text+=`<span class=\"noticeAdmin\">전체 공지사항이 올라왔습니다</span>`;\r\n");
      out.write("      				 text+=`</a>`;	\r\n");
      out.write("      				 text+=`</li>`;	\r\n");
      out.write("      				 \r\n");
      out.write("    			  \r\n");
      out.write("    			  });\r\n");
      out.write("    			  \r\n");
      out.write("    			  $(\".noticeDropdownBar_noticeBody__240wL\").html(text);\r\n");
      out.write("    		\r\n");
      out.write("			}\r\n");
      out.write("     }  */\r\n");
      out.write("    \r\n");
      out.write("    		\r\n");
      out.write("    		/* 프로젝트 자료실  알림 */\r\n");
      out.write("    		\r\n");
      out.write("    /* 	projectLibListOk();\r\n");
      out.write("    		\r\n");
      out.write("    		function projectLibListOk() {\r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				url: \"/main/alarmListOk.ma\",\r\n");
      out.write("    				type:\"get\",\r\n");
      out.write("    				contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("    				success: projectLibReplyOk\r\n");
      out.write("    				\r\n");
      out.write("    			});\r\n");
      out.write("    	    			\r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		function projectLibReplyOk(result) {\r\n");
      out.write("    				\r\n");
      out.write("  			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("  			  let text=\"\";\r\n");
      out.write("  			  var count=0;	\r\n");
      out.write("  			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("  			  \r\n");
      out.write("  				  console.log(result.alarmList)\r\n");
      out.write("  				  count++;\r\n");
      out.write("  			\r\n");
      out.write("  				 text+= `<li class=\"noticeBoardList\">`;                         \r\n");
      out.write("  				 text+=` <a class=\"noticeMoveProjectLib\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/myPage/my_project_lib.jsp\" >`;	\r\n");
      out.write("  				 text+=`<span class=\"noticeProjectLib\">프로젝트 게시판이 올라왔습니다</span>`;\r\n");
      out.write("  				 text+=`</a>`;	\r\n");
      out.write("  				 text+=`</li>`;	\r\n");
      out.write("  			  \r\n");
      out.write("  			  });\r\n");
      out.write("  			  \r\n");
      out.write("  			  $(\".noticeBoardReply\").html(text);\r\n");
      out.write("  		\r\n");
      out.write("			}\r\n");
      out.write("   }  */\r\n");
      out.write("\r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    		/* 프로젝트  공지사항 알림  */\r\n");
      out.write("    /* 		projectNoticeListOk();\r\n");
      out.write("    		\r\n");
      out.write("    		function projectNoticeListOk() {\r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				url: \"/main/alarmListOk.ma\",\r\n");
      out.write("    				type:\"get\",\r\n");
      out.write("    				contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("    				success: projectNoticeOk\r\n");
      out.write("    				\r\n");
      out.write("    			});\r\n");
      out.write("    	    			\r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		function projectNoticeOk(result) {\r\n");
      out.write("    				\r\n");
      out.write("  			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("  			  let text=\"\";\r\n");
      out.write("  			  var count=0;	\r\n");
      out.write("  			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("  			  \r\n");
      out.write("  				  console.log(result.alarmList)\r\n");
      out.write("  				  count++;\r\n");
      out.write("  			\r\n");
      out.write("  				 text+= `<li class=\"projectNotice\">`;                         \r\n");
      out.write("  				 text+=` <a class=\"moveNoticeProject\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/myPage/my_project_notice.jsp\" >`;	\r\n");
      out.write("  				 text+=`<span class=\"noticeProject\">프로젝트 공지사항이 올라왔습니다</span>`;\r\n");
      out.write("  				 text+=`</a>`;	\r\n");
      out.write("  				 text+=`</li>`;	\r\n");
      out.write("  			  \r\n");
      out.write("  			  });\r\n");
      out.write("  			  \r\n");
      out.write("  			  $(\".projectnotice\").html(text);\r\n");
      out.write("  		\r\n");
      out.write("			}\r\n");
      out.write("   } */ \r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    		/* 프로젝트 모집 댓글 알림   */\r\n");
      out.write("    		\r\n");
      out.write("    /* 		projectReplyOk();\r\n");
      out.write("    		\r\n");
      out.write("    		function projectReplyOk() {\r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				url: \"/main/alarmListOk.ma\",\r\n");
      out.write("    				type:\"get\",\r\n");
      out.write("    				contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("    				success: projectNoticeReplyOk\r\n");
      out.write("    				\r\n");
      out.write("    			});\r\n");
      out.write("    	    			\r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		function projectNoticeReplyOk(result) {\r\n");
      out.write("    				\r\n");
      out.write("  			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("  			  let text=\"\";\r\n");
      out.write("  			  var count=0;	\r\n");
      out.write("  			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("  			  \r\n");
      out.write("  				  console.log(result.alarmList)\r\n");
      out.write("  				  count++;\r\n");
      out.write("  			\r\n");
      out.write("  				 text+= `<li class=\"projectReplyNotice\">`;                         \r\n");
      out.write("  				 text+=` <a class=\"moveBoardProject\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardProject.jsp\" >`;	\r\n");
      out.write("  				 text+=`<span class=\"noticeReplyProject\">(프로젝트) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("  				 text+=`</a>`;	\r\n");
      out.write("  				 text+=`</li>`;	\r\n");
      out.write("  			  \r\n");
      out.write("  			  });\r\n");
      out.write("  			  \r\n");
      out.write("  			  $(\".projectReply\").html(text);\r\n");
      out.write("  		\r\n");
      out.write("			}\r\n");
      out.write("   } */ \r\n");
      out.write("    		\r\n");
      out.write("    		/* 스터디 모집 댓글 알림   */\r\n");
      out.write("    		\r\n");
      out.write("/*     		projectStudyOk();\r\n");
      out.write("    		\r\n");
      out.write("    		function projectStudyOk() {\r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				url: \"/main/alarmListOk.ma\",\r\n");
      out.write("    				type:\"get\",\r\n");
      out.write("    				contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("    				success: studyNoticeReplyOk\r\n");
      out.write("    				\r\n");
      out.write("    			});\r\n");
      out.write("    	    			\r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		function studyNoticeReplyOk(result) {\r\n");
      out.write("    				\r\n");
      out.write("  			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("  			  let text=\"\";\r\n");
      out.write("  			  var count=0;	\r\n");
      out.write("  			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("  			  \r\n");
      out.write("  				  console.log(result.alarmList)\r\n");
      out.write("  				  count++;\r\n");
      out.write("  			\r\n");
      out.write("  				 text+= `<li class=\"studyReplyNotice\">`;                         \r\n");
      out.write("  				 text+=` <a class=\"moveBoardStudy\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardStudy.jsp\" >`;	\r\n");
      out.write("  				 text+=`<span class=\"noticeReplyStudy\">(스터디) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("  				 text+=`</a>`;	\r\n");
      out.write("  				 text+=`</li>`;	\r\n");
      out.write("  			  \r\n");
      out.write("  			  });\r\n");
      out.write("  			  \r\n");
      out.write("  			  $(\".projectStudyReply\").html(text);\r\n");
      out.write("  		\r\n");
      out.write("			}\r\n");
      out.write("   } \r\n");
      out.write(" */    		\r\n");
      out.write("\r\n");
      out.write("    		\r\n");
      out.write("    		<!-- 프로젝트 (컴퍼니) 모집함  -->\r\n");
      out.write("    		\r\n");
      out.write("/*     		projectCompanyOk();\r\n");
      out.write("    		\r\n");
      out.write("    		function projectCompanyOk() {\r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				url: \"/main/alarmListOk.ma\",\r\n");
      out.write("    				type:\"get\",\r\n");
      out.write("    				contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("    				success: projectCompanyReplyOk\r\n");
      out.write("    				\r\n");
      out.write("    			});\r\n");
      out.write("    	    			\r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		function projectCompanyReplyOk(result) {\r\n");
      out.write("    				\r\n");
      out.write("  			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("  			  let text=\"\";\r\n");
      out.write("  			  var count=0;	\r\n");
      out.write("  			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("  			  \r\n");
      out.write("  				  console.log(result.alarmList)\r\n");
      out.write("  				  count++;\r\n");
      out.write("  			\r\n");
      out.write("  				 text+= `<li class=\"projectCompanyReplyNotice\">`;                         \r\n");
      out.write("  				 text+=`<a class=\"moveBoardProjectCompany\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardProject_company.jsp\" >`;	\r\n");
      out.write("  				 text+=`<span class=\"noticeReplyProjectCompany\">(프로젝트 회사) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("  				 text+=`</a>`;	\r\n");
      out.write("  				 text+=`</li>`;	\r\n");
      out.write("  			  \r\n");
      out.write("  			  });\r\n");
      out.write("  			  \r\n");
      out.write("  			  $(\".projectCompanyReply\").html(text);\r\n");
      out.write("  		\r\n");
      out.write("			}\r\n");
      out.write("   } \r\n");
      out.write(" */\r\n");
      out.write("    		\r\n");
      out.write("    		<!-- 스터디 (컴퍼니) 모집함  -->\r\n");
      out.write("    		\r\n");
      out.write("/*     		studyCompanyOk();\r\n");
      out.write("    		\r\n");
      out.write("    		function studyCompanyOk() {\r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				url: \"/main/alarmListOk.ma\",\r\n");
      out.write("    				type:\"get\",\r\n");
      out.write("    				contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("    				success: studyCompanyReplyOk\r\n");
      out.write("    				\r\n");
      out.write("    			});\r\n");
      out.write("    	    			\r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		function studyCompanyReplyOk(result) {\r\n");
      out.write("    				\r\n");
      out.write("  			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("  			  let text=\"\";\r\n");
      out.write("  			  var count=0;	\r\n");
      out.write("  			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("  			  \r\n");
      out.write("  				  console.log(result.alarmList)\r\n");
      out.write("  				  count++;\r\n");
      out.write("  			\r\n");
      out.write("  				 text+= `<li class=\"studyCompanyReplyNotice\">`;                         \r\n");
      out.write("  				 text+=`<a class=\"moveBoardStudyCompany\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/board/boardStudy_company.jsp\" >`;	\r\n");
      out.write("  				 text+=`<span class=\"noticeReplyStudyCompany\">(스터디 회사) 모집글 댓글이 달렸습니다</span>`;\r\n");
      out.write("  				 text+=`</a>`;	\r\n");
      out.write("  				 text+=`</li>`;	\r\n");
      out.write("  			  \r\n");
      out.write("  			  });\r\n");
      out.write("  			  \r\n");
      out.write("  			  $(\".studyCompanyReply\").html(text);\r\n");
      out.write("  		\r\n");
      out.write("			}\r\n");
      out.write("   }  */\r\n");
      out.write("    		\r\n");
      out.write("\r\n");
      out.write("    		\r\n");
      out.write("    		<!-- 전체 공지사항 알람 띵동  -->\r\n");
      out.write("    		\r\n");
      out.write("    	/* 	adminListOk();\r\n");
      out.write("    		\r\n");
      out.write("    		function adminListOk() {\r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				url: \"/main/alarmListOk.ma\",\r\n");
      out.write("    				type:\"get\",\r\n");
      out.write("    				contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("    				success: adminNoticeOk\r\n");
      out.write("    				\r\n");
      out.write("    			});\r\n");
      out.write("    	    			\r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		function adminNoticeOk(result) {\r\n");
      out.write("    				\r\n");
      out.write("  			  var resultAlarmListOk = JSON.parse(result);\r\n");
      out.write("				  if(resultAlarmListOk.length > 0){\r\n");
      out.write("  			  let text=\"\";\r\n");
      out.write("  			  var count=0;	\r\n");
      out.write("  			  resultAlarmListOk.forEach(result=>{\r\n");
      out.write("  			  \r\n");
      out.write("  				  console.log(result.alarmList)\r\n");
      out.write("  				  count++;\r\n");
      out.write("  			\r\n");
      out.write("  				 text+= `<li class=\"adminNotice1\">`;                         \r\n");
      out.write("  				 text+=`<a class=\"moveAdminNotice\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/allNotice.jsp\" >`;	\r\n");
      out.write("  				 text+=`<span class=\"noticeAdmin\">전체 공지사항이 올라왔습니다</span>`;\r\n");
      out.write("  				 text+=`</a>`;	\r\n");
      out.write("  				 text+=`</li>`;	\r\n");
      out.write("  			  \r\n");
      out.write("  			  });\r\n");
      out.write("  			  \r\n");
      out.write("  			  $(\".adminNotice\").html(text);\r\n");
      out.write("  		\r\n");
      out.write("			}\r\n");
      out.write("   } \r\n");
      out.write("    		 */\r\n");
      out.write("    		\r\n");
      out.write("    		 function searchSend(){\r\n");
      out.write("                 var content = searchForm.header_search_input.value;\r\n");
      out.write("                 if(!content){\r\n");
      out.write("                    alert(\"검색어를 입력하세요\");\r\n");
      out.write("                    return;\r\n");
      out.write("                 }\r\n");
      out.write("                 \r\n");
      out.write("                 searchForm.submit()\r\n");
      out.write("              }       \r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    		 function alarmSend(){\r\n");
      out.write("                 var content = searchForm.header_search_input.value;\r\n");
      out.write("                 if(!content){\r\n");
      out.write("                    alert(\"서비스 준비 중 입니다\");\r\n");
      out.write("                    return;\r\n");
      out.write("                 }\r\n");
      out.write("                 \r\n");
      out.write("                 searchForm.submit()\r\n");
      out.write("              }       \r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    		");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /app/fix/header_notice.jsp(47,22) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUserNumber eq 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		                        <li class=\"dropdownBar_menuItem_header\">\r\n");
          out.write("		                            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/homeListOk.ad\" style=\"display: inline-block;\">관리자 페이지</a>\r\n");
          out.write("		                        </li>\r\n");
          out.write("		                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }
}
