/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-26 02:48:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardApply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>지원자 정보</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/board/boardApply.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"search_results\" style=\"margin-top: 50px;\">\r\n");
      out.write("		<a\r\n");
      out.write("			href=\"history.back()\">\r\n");
      out.write("			<svg stroke=\"currentColosr\" fill=\"currentColor\" stroke-width=\"0\"\r\n");
      out.write("				viewBox=\"0 0 448 512\" color=\"808080\" cursor=\"pointer\" height=\"30\"\r\n");
      out.write("				width=\"30\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("				style=\"color: rgb(128, 128, 128);\">\r\n");
      out.write("         <path\r\n");
      out.write("					d=\"M257.5 445.1l-22.2 22.2c-9.4 9.4-24.6 9.4-33.90L7\r\n");
      out.write("          273c-9.4-9.4-9.4-24.6 0-33.9L201.4 44.7c9.4-9.4 24.6-9.4 33.9 0l22.2 22.2c9.5 9.5\r\n");
      out.write("           9.3 25-.4 34.3L136.6 216H424c13.3 0 24 10.7 24 24v32c0 13.3-10.7 24-24 24H136.6l120.5 114.8c9.8 9.3 10 24.8.4 34.3z\"></path>\r\n");
      out.write("       </svg>\r\n");
      out.write("		</a>\r\n");
      out.write("		<div class=\"ui segments\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"ui segment\">\r\n");
      out.write("				<div class=\"header\">\r\n");
      out.write("					<span class=\"desc\"> 지원자 정보 </span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"ui segment\">\r\n");
      out.write("				<div class=\"ui items\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"ui segment\">\r\n");
      out.write("						<div class=\"ui user card\" data-search-item-user-id=\"203605\"\r\n");
      out.write("							relationship-data-setted=\"true\">\r\n");
      out.write("							<div class=\"image\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/cosmosProfile.png\"\r\n");
      out.write("									alt=\"\" class=\"ui circular image lazyloaded\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"stackable content\">\r\n");
      out.write("								<div class=\"main\">\r\n");
      out.write("									<div class=\"user-name\">\r\n");
      out.write("										<span class=\"name\">HDS</span>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"user-title nowrap\">\r\n");
      out.write("										<span class=\"job-title\">경력 20년</span>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"nowrap meta\">All Language</div>\r\n");
      out.write("									<div class=\"ui divider visible-if-relationship-exists\"\r\n");
      out.write("										style=\"display: none\"></div>\r\n");
      out.write("									<div class=\"relationship-extra-info\">\r\n");
      out.write("										<div class=\"relationship\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"extra\">\r\n");
      out.write("									<div class=\"request-button\"\r\n");
      out.write("										data-url=\"/api/users/324116/request_button\">\r\n");
      out.write("										<div class=\"ui mini basic buttons\" onclick=\"handleClick()\">\r\n");
      out.write("											<a class=\"ui basic button\" onclick=\"handleClick()\"> 합격 </a>\r\n");
      out.write("											<a class=\"ui basic button\"> 불합격 </a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"ui divider\"></div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"ui user card\" data-search-item-user-id=\"203605\"\r\n");
      out.write("							relationship-data-setted=\"true\">\r\n");
      out.write("							<div class=\"image\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/cosmosProfile.png\"\r\n");
      out.write("									alt=\"\" class=\"ui circular image lazyloaded\" src=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"stackable content\">\r\n");
      out.write("								<div class=\"main\">\r\n");
      out.write("									<div class=\"user-name\">\r\n");
      out.write("										<span class=\"name\">루피</span>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"user-title nowrap\">\r\n");
      out.write("										<span class=\"job-title\">경력 8년</span>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"nowrap meta\">php</div>\r\n");
      out.write("									<div class=\"ui divider visible-if-relationship-exists\"\r\n");
      out.write("										style=\"display: none\"></div>\r\n");
      out.write("									<div class=\"relationship-extra-info\">\r\n");
      out.write("										<div class=\"relationship\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"extra\">\r\n");
      out.write("									<div class=\"request-button\"\r\n");
      out.write("										data-url=\"/api/users/324116/request_button\">\r\n");
      out.write("										<div class=\"ui mini basic buttons\">\r\n");
      out.write("											<a class=\"ui basic button\" onclick=\"init()\">합격</a> <a\r\n");
      out.write("												class=\"ui basic button\">불합격</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"pagination\" onclick=\"handleClick()\">\r\n");
      out.write("		<a href=\"#\">&laquo;</a> <a class=\"active\" href=\"#\">1</a> <a\r\n");
      out.write("			class=\"num\" href=\"#\">2</a> <a class=\"num\" href=\"#\">3</a> <a\r\n");
      out.write("			class=\"num\" href=\"#\">4</a> <a class=\"num\" href=\"#\">5</a> <a href=\"#\">&raquo;</a>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$('.pagination .num,.active').on(\"click\", function() {\r\n");
      out.write("		$(\".pagination .num,.active.active\").removeClass('active');\r\n");
      out.write("		$(this).addClass(\"active\");\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
