/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-11-14 11:13:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardComment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>댓글 등록</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/board/boardProject2.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style =\"overflow: auto;\">\r\n");
      out.write("    <div id=\"root\">\r\n");
      out.write("        <div class=\"studyContent_postWrapper\">\r\n");
      out.write("            <section class=\"studyContent_postHeader\">\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/main/index.jsp\">\r\n");
      out.write("          <svg stroke=\"currentColosr\" fill=\"currentColor\" stroke-width=\"0\"\r\n");
      out.write("        viewBox=\"0 0 448 512\" color=\"808080\" cursor=\"pointer\" height=\"30\" width=\"30\"\r\n");
      out.write("         xmlns=\"http://www.w3.org/2000/svg\" style=\"color: rgb(128, 128, 128);\" >\r\n");
      out.write("         <path d=\"M257.5 445.1l-22.2 22.2c-9.4 9.4-24.6 9.4-33.90L7\r\n");
      out.write("          273c-9.4-9.4-9.4-24.6 0-33.9L201.4 44.7c9.4-9.4 24.6-9.4 33.9 0l22.2 22.2c9.5 9.5\r\n");
      out.write("           9.3 25-.4 34.3L136.6 216H424c13.3 0 24 10.7 24 24v32c0 13.3-10.7 24-24 24H136.6l120.5 114.8c9.8 9.3 10 24.8.4 34.3z\"\r\n");
      out.write("           ></path>\r\n");
      out.write("       </svg>\r\n");
      out.write("       </a>\r\n");
      out.write("                <div class=\"studyContent_title\">Cosmos Team Project 인원 모집합니다 ! </div>\r\n");
      out.write("                <div class=\"studyContent_userAndDate\">\r\n");
      out.write("                    <img class=\"studyContent_userImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/cosmosProfile.png\">\r\n");
      out.write("                <div class=\"studyContent_userName\">hyun</div>\r\n");
      out.write("                <div class=\"studyContent_registeredDate\">2022.10.04</div>\r\n");
      out.write("                </div>\r\n");
      out.write("          <!--       <section class=\"studyButtons_buttonWrapper\">\r\n");
      out.write("                    <button class=\"studyButtons_buttons\">마감</button>\r\n");
      out.write("                    <button class=\"studyButtons_buttons\">수정</button>\r\n");
      out.write("                    <button class=\"studyButtons_buttons\">삭제</button>\r\n");
      out.write("                </section> -->\r\n");
      out.write("                <div class=\"recommendPost_totalWrapper\">\r\n");
      out.write("                    <div class=\"recommendPost_recommendWrapper\">\r\n");
      out.write("                        <div class=\"recommendPost_userInfoWrapper\">\r\n");
      out.write("                            <div class=\"recommendPost_bar\"></div>\r\n");
      out.write("                            <div class=\"recommendPost_userInfo\">\r\n");
      out.write("                                <span class=\"recommendPost_userName\">COSMOS</span>\r\n");
      out.write("                                최신글 목록\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"recommendPost_listWrapper\">\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">1.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">사이드 프로젝트 프론트엔드, 백엔드 개발자분 모집합니다</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">2.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">사이드 프로젝트를 진행하실 프론트엔드 2분 모집합니다</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">3.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">본격적으로 딴짓 사이드 프로젝트 프론트엔드 개발자 구인!</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">4.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">사이드 프로젝트 팀원 모집</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">5.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">(두개의 스터디 모집 중) 만들면서 배우는 클린 아키텍처 / Hibernate 만들어보기</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">6.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">[UI, UX 디자이너] 취업용 포트폴리오를 만드실 디자이너 한 분 충원합니다 !</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">7.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">태블릿펜을 통한 그림심리검사앱</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">8.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">신림역 주변 모각코 </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">9.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">[디스코드] 온라인 모각코 얼른 오세요 .. !</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"recommendPost_postList\">\r\n");
      out.write("                                <div class=\"recommendPost_index\">10.</div>\r\n");
      out.write("                                <div class=\"recommendPost_title\">채용혜택) 2022년 NH투자증권 빅데이터 경진대회</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>        \r\n");
      out.write("                <ul class=\"studyGrid\">\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                        <span class=\"studyInfo_title\">모집 구분</span>\r\n");
      out.write("                        <span class=\"studyInfo_content\">프로젝트</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                        <span class=\"studyInfo_title\">진행방식</span>\r\n");
      out.write("                        <span class=\"studyInfo_content\">&nbsp;온라인</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                        <span class=\"studyInfo_title\">모집 인원</span>\r\n");
      out.write("                        <span class=\"studyInfo_content\">6명</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                        <span class=\"studyInfo_title\">지원 인원</span>\r\n");
      out.write("                         <!--   <span class=\"studyInfo_content\" style=\"color:rgb(223, 65, 65)\">10명</span>  -->\r\n");
      out.write("                        <span class=\"studyInfo_content\" style=\"color:green\">0명</span> \r\n");
      out.write("                        <a class =\"apply_list\" href=\"boardApply.jsp\" rel=\"noreferrer\" target=\"_blank\">\r\n");
      out.write("                            <span class = \"apply_info\">지원자 정보</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                        <span class=\"studyInfo_title\">연락 방법</span>\r\n");
      out.write("                        <div class=\"contact_project\">\r\n");
      out.write("                            <a class =\"project_link\" href=\"\" rel=\"noreferrer\" target=\"_blank\">\r\n");
      out.write("                                <span class = \"project\">지원하기</span>\r\n");
      out.write("                                \r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                        <span class=\"studyInfo_title\">예상 기간</span>\r\n");
      out.write("                        <span class=\"studyInfo_content\">3주</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                        <span class=\"studyInfo_title\">사용 언어</span>\r\n");
      out.write("                        <ul class=\"studyInfo_languageList\">\r\n");
      out.write("                            <li class=\"studyInfo_language\">\r\n");
      out.write("                                <img class=\"studyInfo_languageImage\" src=\"https://holaworld.io/images/languages/javascript.svg\" alt=\"language\">\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"studyInfo\">\r\n");
      out.write("                            <span class=\"studyInfo_title\">시작 예정</span>\r\n");
      out.write("                            <span class=\"studyInfo_content\">2022.10.04</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </section>\r\n");
      out.write("                <div class=\"studyContent_postContentWrapper\">\r\n");
      out.write("                    <h2 class=\"studyContent_postInfo\">프로젝트 소개</h2>\r\n");
      out.write("                    <div class=\"studyContent_postContent\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <br>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <img src=\"https://www.designdb.com/usr/upload/editor/data/20220905175148b669a241-69a2-45ff-b396-ffa90b7110cc.png\">\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <br>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>○ 접수방법</p>\r\n");
      out.write("                        <p>- 참가신청서 링크:&nbsp;\r\n");
      out.write("                            <a href=\"https://forms.gle/cSXHY9yPfVuzyenz7\" target=\"_blank\">https://forms.gle/cSXHY9yPfVuzyenz7</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>- 상세 대회 정보:&nbsp;\r\n");
      out.write("                            <a href=\"https://aifactory.space/competition/detail/2105\" target=\"_blank\">https://aifactory.space/competition/detail/2105</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>&nbsp;</p>\r\n");
      out.write("                        <p>○ 공모 과제</p>\r\n");
      out.write("                        <p>- 장기 천연가스 수요 예측 모델 개발</p>\r\n");
      out.write("                        <p>- 생산기지 BOG(Boil Off Gas; 증발가스) 최적가동 예측 모델 개발</p>\r\n");
      out.write("                        <p>&nbsp;</p>\r\n");
      out.write("                        <p>○ 주최/주관/후원/운영</p>\r\n");
      out.write("                        <p>- 주최/주관: 한국가스공사</p>\r\n");
      out.write("                        <p>- 후원: 마이크로소프트</p>\r\n");
      out.write("                        <p>- 운영: AIFactory</p>\r\n");
      out.write("                        <p>&nbsp;</p>\r\n");
      out.write("                        <p>○ 참가자격</p>\r\n");
      out.write("                        <p>- 모집구분: 스타트업, 예비창업가(스타트업을 제외한 모두)</p>\r\n");
      out.write("                        <p>- 14세 이상의 대한민국 국적을 가진 사람 누구나 개인 및 팀(최대 4인)</p>\r\n");
      out.write("                        <p>※ 한 개인이 두 개 이상의 팀에 중복 참여 불가</p>\r\n");
      out.write("                        <p>&nbsp;</p>\r\n");
      out.write("                        <p>○ 기간 및 일정</p>\r\n");
      out.write("                        <p>- 참가자 모집 및 기획안 접수기간 : 8월 29일(월) ~ 9월 25일(일)</p>\r\n");
      out.write("                        <p>- 사전 설명회 (온라인) :&nbsp;\r\n");
      out.write("                            <a href=\"https://aifactory.space/competition/detail/2119\" target=\"_blank\">https://aifactory.space/competition/detail/2119</a>&nbsp;9월 14일(수)\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>- 예선 기간 : 9월 30일 ~ 10월 23일</p>\r\n");
      out.write("                        <p>- 본선 기간 : 10월 28일 ~ 12월 12일</p>\r\n");
      out.write("                        <p>- 시상식 (온라인 진행) : 12월 15일</p>\r\n");
      out.write("                        <p>※ 위 일정 및 장소는 사정상 변동될 수 있습니다.</p>\r\n");
      out.write("                        <p>&nbsp;</p>\r\n");
      out.write("                        <p>○ 상금 (총 상금 7000만원, 총 24팀, 전원 한국가스공사 사장상)</p>\r\n");
      out.write("                        <p>- [과제1] 대상 : 예비창업가 500만원(1팀), 스타트업 1,000만원(1팀)</p>\r\n");
      out.write("                        <p>- [과제1] 최우수상 : 예비창업가 300만원(1팀), 스타트업 500만원(1팀)</p>\r\n");
      out.write("                        <p>- [과제1] 우수상 : 예비창업가 150만원(2팀), 스타트업 250만원(2팀)</p>\r\n");
      out.write("                        <p>- [과제1] 특별상 : 예비창업가 100만원(2팀), 스타트업 100만원(2팀)</p>\r\n");
      out.write("                        <p>- [과제2] 대상 : 예비창업가 500만원(1팀), 스타트업 1,000만원(1팀)</p>\r\n");
      out.write("                        <p>- [과제2] 최우수상 : 예비창업가 300만원(1팀), 스타트업 500만원(1팀)</p>\r\n");
      out.write("                        <p>- [과제2] 우수상 : 예비창업가 150만원(2팀), 스타트업 250만원(2팀)</p>\r\n");
      out.write("                        <p>- [과제2] 특별상 : 예비창업가 100만원(2팀), 스타트업 100만원(2팀)</p>\r\n");
      out.write("                        <p>- ※ 위 상금 규모는 사정상 변동될 수 있습니다.</p>\r\n");
      out.write("                        <p>&nbsp;</p>\r\n");
      out.write("                        <p>○ 수상자 혜택</p>\r\n");
      out.write("                        <p>- Kogas 내 중소기업기술개발 지원사업 지원 시 우대</p>\r\n");
      out.write("                        <p>- Microsoft 글로벌창업사관학교 지원 시 우대</p>\r\n");
      out.write("                        <p>- Microsoft Startup 프로그램 지원 시 우대</p>\r\n");
      out.write("                        <p>- Microsoft Azure Credit 일부 지원</p>\r\n");
      out.write("                        <p>&nbsp;</p>\r\n");
      out.write("                        <p>○ 문의</p>\r\n");
      out.write("                        <p>- 대회 운영 관련: 인공지능팩토리,\r\n");
      out.write("                             <a href=\"mailto:cs@aifactory.page\" target=\"_blank\">cs@aifactory.page</a>,\r\n");
      out.write("                              ☎ 042-710-6451</p>\r\n");
      out.write("                              <p>- 시상 및 혜택 문의: 디지털 뉴딜기획부 담당자,&nbsp;\r\n");
      out.write("                                <a href=\"mailto:wjddnlove110@kogas.or.kr\" target=\"_blank\">wjddnlove110@kogas.or.kr</a>,\r\n");
      out.write("                                 ☎ 053-670-0709</p><p>&nbsp;</p>\r\n");
      out.write("                                 <p>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    <section class=\"studyContent_commentAndViews\">\r\n");
      out.write("                        <div class=\"studyContent_postComment\">\r\n");
      out.write("                            <div class=\"commentInput_commentInput\">\r\n");
      out.write("                                <h1 class=\"commentInput_commentCount\">1개의 댓글이 있습니다.</h1><!-- 댓글 등록하면 count증가 -->\r\n");
      out.write("                                <textarea class=\"commentInput_commentText\" placeholder=\"댓글을 입력하세요.\"></textarea>\r\n");
      out.write("                                <div class=\"commentInput_buttonWrapper\">\r\n");
      out.write("                                    <button class=\"commentInput_buttonComplete\" name=\"register\">댓글 등록</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <ul class=\"commentList_CommentList\">\r\n");
      out.write("                                    <li class=\"commentItem_commentContainer\">\r\n");
      out.write("                                        <section class=\"commentItem_commentHeader\">\r\n");
      out.write("                                            <div class=\"commentItem_avatarWrapper\">\r\n");
      out.write("                                                <img class=\"commentItem_userImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/cosmosProfile.png\" alt=\"사용자 이미지\">\r\n");
      out.write("                                                <div class=\"commentItem_commentInfo\">\r\n");
      out.write("                                                    <div class=\"commentItem_title\">\r\n");
      out.write("                                                        <div class=\"commentItem_userNickname\">hyun</div>\r\n");
      out.write("                                                        <div class=\"commentItem_registeredDate\">2022-10-01 16:25:17</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <section class=\"commentButtons_buttonWrapper\">\r\n");
      out.write("                                                <button class=\"commentButtons_buttons\">수정</button>\r\n");
      out.write("                                                <button class=\"commentButtons_buttons\">삭제</button>\r\n");
      out.write("                                            </section>\r\n");
      out.write("                                        </section>\r\n");
      out.write("                                        <section class=\"commentItem_commentContent\">\r\n");
      out.write("                                            <p class=\"commentItem_commentContent\">안녕</p>\r\n");
      out.write("                                        </section>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
