/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-23 13:27:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/gb_0900_csh/jsp/workspace/cosmos-project/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/gb_0900_csh/jsp/workspace/cosmos-project/WebContent/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1665992284967L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>프로젝트/스터디 생성</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\"	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/fix/cosmosProfile.png\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/board/newPage.css\"> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/writeOk.bo\" method=\"post\" name=\"newPage\">\r\n");
      out.write("	<div id=\"root\">\r\n");
      out.write("        <div class=\"postRegister_postWrapper__1s7mv\">\r\n");
      out.write("            <a href=\"javascript:;\" onclick=\"history.back()\">\r\n");
      out.write("                <svg stroke=\"currentColosr\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 448 512\" color=\"808080\"\r\n");
      out.write("                    cursor=\"pointer\" height=\"30\" width=\"30\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                    <path\r\n");
      out.write("                        d=\"M 257.5 445.1 l -22.2 22.2 c -9.4 9.4 -24.6 9.4 -33.9 0 L 7 273 c -9.4 -9.4 -9.4 -24.6 0 -33.9 L 201.4 44.7 c 9.4 -9.4 24.6 -9.4 33.9 0 l 22.2 22.2 c 9.5 9.5 9.3 25 -0.4 34.3 L 136.6 216 H 424 c 13.3 0 24 10.7 24 24 v 32 c 0 13.3 -10.7 24 -24 24 H 136.6 l 120.5 114.8 c 9.8 9.3 10 24.8 0.4 34.3 Z\"\r\n");
      out.write("                        style=\"color: rgb(128, 128, 128);\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <section>\r\n");
      out.write("                <div class=\"postRegister_postContentWrapper__3BXZ6\">\r\n");
      out.write("                    <span class=\"postRegister_sequence__nC1Px\">1</span>\r\n");
      out.write("                    <h2 class=\"postRegister_text__17jg3\">프로젝트 기본 정보를 입력해주세요.</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"postinfo_inputList__3SKF-\">\r\n");
      out.write("                    <!-- 모집구분  -->\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <label class=\"selectbox_labelText__3Q9iz\" for=\"onoffline\">모집 구분\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div class=\"css-2b097c-container css_newT\">\r\n");
      out.write("                            <span aria-live=\"polite\" aria-atomic=\"false\" aria-relevant=\"additions text\"\r\n");
      out.write("                                class=\"css-7pg0cj-a11yText\"></span>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"select__control css-1iewm1a-control\">\r\n");
      out.write("                                <div class=\"select__value-container css-1hwfws3\">\r\n");
      out.write("                                    <!-- 이거다 -->\r\n");
      out.write("                                    <!-- 스터디/프로젝트 바 -->\r\n");
      out.write("                                    <div class=\"css-1g6gooi\">\r\n");
      out.write("                                        <div name=\"Category\" class=\"select__placeholder css-1wa3eu0-placeholder\">스터디/프로젝트</div>\r\n");
      out.write("                                        <input style=\"display:none !important;\" name=\"boardCategory\">\r\n");
      out.write("                                        <div class=\"select__input\" style=\"display:inline-block;\">\r\n");
      out.write("\r\n");
      out.write("                                            <input autocapitalize=\"none\" autocomplete=\"off\" autocorrect=\"off\"\r\n");
      out.write("                                                id=\"react-select-2-input\" spellcheck=\"false\" tabindex=\"0\" type=\"text\"\r\n");
      out.write("                                                aria-autocomplete=\"list\" value=\"\"\r\n");
      out.write("                                                style=\"box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 0; outline: 0px; padding: 0px; color: inherit;\">\r\n");
      out.write("                                            <div\r\n");
      out.write("                                                style=\"position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 16px; font-family: Arial; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"select__indicators css-1wy0on6\">\r\n");
      out.write("                                    <span class=\"select__indicator-separator css-1okebmr-indicatorSeparator\"></span>\r\n");
      out.write("                                    <div class=\"select__indicator select__dropdown-indicator css-tlfecz-indicatorContainer\"\r\n");
      out.write("                                        aria-hidden=\"true\">\r\n");
      out.write("                                        <svg height=\"20\" width=\"20\" viewBox=\"0 0 20 20\" aria-hidden=\"true\"\r\n");
      out.write("                                            focusable=\"false\" class=\"css-8mmkcg\">\r\n");
      out.write("                                            <path\r\n");
      out.write("                                                d=\"M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z\">\r\n");
      out.write("                                            </path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 더보기 버튼 누르면 나오는 div  -->\r\n");
      out.write("                            <div class=\"select__menu css-26l3qy-menu newInAction\">\r\n");
      out.write("                                <div class=\"select__menu-list css-11unzgr\">\r\n");
      out.write("                                    <div class=\"select__option select__option--is-focused css-1n7v3ny-option\"\r\n");
      out.write("                                        id=\"react-select-2-option-0\" tabindex=\"-1\">프로젝트</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-2-option-1\"\r\n");
      out.write("                                        tabindex=\"-1\">스터디</div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 더보기 버튼 누르면 나오는 div 마지막  -->\r\n");
      out.write("\r\n");
      out.write("                            <input name=\"onoffline\" type=\"hidden\" value=\"1\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 모집 인원 -->\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <label class=\"selectbox_labelText__3Q9iz\" for=\"onoffline\">모집 인원</label>\r\n");
      out.write("                        <div class=\"postinfo_contactInput__3nnsb\" style=\"margin:0 auto;\">\r\n");
      out.write("                            <input type=\"text\" class=\"input_customInput__1e1Il\" name=\"boardRecruitNumber\" autocomplete=\"off\" placeholder=\"인원 수는 숫자만 입력해주세요\" value=\"\" oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"postinfo_inputList__3SKF-\">\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <!-- 진행 방식 -->\r\n");
      out.write("                        <label class=\"selectbox_labelText__3Q9iz\" for=\"onoffline\">진행 방식</label>\r\n");
      out.write("                        <div class=\" css-2b097c-container css_newT2\">\r\n");
      out.write("                            <span aria-live=\"polite\" aria-atomic=\"false\" aria-relevant=\"additions text\"\r\n");
      out.write("                                class=\"css-7pg0cj-a11yText\"></span>\r\n");
      out.write("                            <div class=\"select__control css-1iewm1a-control \">\r\n");
      out.write("                                <div class=\"select__value-container css-1hwfws3\">\r\n");
      out.write("                                    <!-- 안에 온라인 / 오프라인 바  -->\r\n");
      out.write("                                    <div name=\"Way\" class=\"select__placeholder css-1wa3eu0-placeholder\" >온라인/오프라인</div>\r\n");
      out.write("                                    <input style=\"display:none !important;\" name=\"boardWay\">\r\n");
      out.write("                                    <div class=\"css-1g6gooi\">\r\n");
      out.write("                                        <div class=\"select__input\" style=\"display: inline-block;\">\r\n");
      out.write("                                            <input autocapitalize=\"none\" autocomplete=\"off\" autocorrect=\"off\"\r\n");
      out.write("                                                id=\"react-select-4-input\" spellcheck=\"false\" tabindex=\"0\" type=\"text\"\r\n");
      out.write("                                                aria-autocomplete=\"list\" value=\"\"\r\n");
      out.write("                                                style=\"box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; outline: 0px; padding: 0px; color: inherit;\">\r\n");
      out.write("                                            <div\r\n");
      out.write("                                                style=\"position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 16px; font-family: Arial; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;\">\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"select__indicators css-1wy0on6\">\r\n");
      out.write("                                    <span class=\"select__indicator-separator css-1okebmr-indicatorSeparator\"></span>\r\n");
      out.write("                                    <div class=\"select__indicator select__dropdown-indicator css-tlfecz-indicatorContainer\"\r\n");
      out.write("                                        aria-hidden=\"true\">\r\n");
      out.write("                                        <svg height=\"20\" width=\"20\" viewBox=\"0 0 20 20\" aria-hidden=\"true\"\r\n");
      out.write("                                            focusable=\"false\" class=\"css-8mmkcg\">\r\n");
      out.write("                                            <path\r\n");
      out.write("                                                d=\"M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z\">\r\n");
      out.write("                                            </path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 진행 방식 더보기 창 div -->\r\n");
      out.write("                            <div class=\"select__menu css-26l3qy-menu newInAction\">\r\n");
      out.write("                                <div class=\"select__menu-list css-11unzgr\">\r\n");
      out.write("                                    <div class=\"select__option select__option--is-focused css-1n7v3ny-option\"\r\n");
      out.write("                                        id=\"react-select-4-option-0\" tabindex=\"-1\">온라인</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-4-option-1\"\r\n");
      out.write("                                        tabindex=\"-1\">오프라인</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input name=\"onoffline\" type=\"hidden\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <!-- 진행 기간  --> <label class=\"selectbox_labelText__3Q9iz\" for=\"onoffline\">진행 기간</label>\r\n");
      out.write("                        <div class=\" css-2b097c-container css_newT3\">\r\n");
      out.write("                            <span aria-live=\"polite\" aria-atomic=\"false\" aria-relevant=\"additions text\"\r\n");
      out.write("                                class=\"css-7pg0cj-a11yText\"></span>\r\n");
      out.write("                            <div class=\"select__control css-1iewm1a-control\">\r\n");
      out.write("                                <div class=\"select__value-container css-1hwfws3\">\r\n");
      out.write("                                    <!-- 기간 미정 ~ 6개월 이상 선택 바  -->\r\n");
      out.write("                                    <div name=\"Period\" class=\"select__placeholder css-1wa3eu0-placeholder\" >기간 미정~6개월 이상</div>\r\n");
      out.write("                                    <input style=\"display:none !important;\" name=\"boardPeriod\">\r\n");
      out.write("                                    <div class=\"css-1g6gooi\">\r\n");
      out.write("                                        <div class=\"select__input\" style=\"display: inline-block;\">\r\n");
      out.write("                                            <input autocapitalize=\"none\" autocomplete=\"off\" autocorrect=\"off\"\r\n");
      out.write("                                                id=\"react-select-5-input\" spellcheck=\"false\" tabindex=\"0\" type=\"text\"\r\n");
      out.write("                                                aria-autocomplete=\"list\" value=\"\"\r\n");
      out.write("                                                style=\"box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; outline: 0px; padding: 0px; color: inherit;\">\r\n");
      out.write("\r\n");
      out.write("                                            <div\r\n");
      out.write("                                                style=\"position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 16px; font-family: Arial; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;\">\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"select__indicators css-1wy0on6\">\r\n");
      out.write("                                    <span class=\"select__indicator-separator css-1okebmr-indicatorSeparator\"></span>\r\n");
      out.write("                                    <div class=\"select__indicator select__dropdown-indicator css-tlfecz-indicatorContainer\"\r\n");
      out.write("                                        aria-hidden=\"true\">\r\n");
      out.write("                                        <svg height=\"20\" width=\"20\" viewBox=\"0 0 20 20\" aria-hidden=\"true\"\r\n");
      out.write("                                            focusable=\"false\" class=\"css-8mmkcg\">\r\n");
      out.write("                                            <path\r\n");
      out.write("                                                d=\"M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z\">\r\n");
      out.write("                                            </path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 진행기간 누르면 더 보기 DIV  -->\r\n");
      out.write("                            <div class=\"select__menu css-26l3qy-menu newInAction\">\r\n");
      out.write("                                <div class=\"select__menu-list css-11unzgr\">\r\n");
      out.write("                                    <div class=\"select__option select__option--is-focused css-1n7v3ny-option\" id=\"react-select-3-option-0\" tabindex=\"-1\">기간 미정</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-1\" tabindex=\"-1\">1개월</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-2\" tabindex=\"-1\">2개월</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-3\" tabindex=\"-1\">3개월</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-4\" tabindex=\"-1\">4개월</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-5\" tabindex=\"-1\">5개월</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-6\" tabindex=\"-1\">6개월</div>\r\n");
      out.write("                                    <div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-7\" tabindex=\"-1\">장기</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <input name=\"onoffline\" type=\"hidden\" value=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!--기술 택 , 시작 예정일   -->\r\n");
      out.write("                <ul class=\"postinfo_inputList__3SKF-\">\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <!-- 기술 스택 --> \r\n");
      out.write("                        <label class=\"selectbox_labelText__3Q9iz\" for=\"onoffline\">기술 스택</label>\r\n");
      out.write("                        <div class=\"setting_LanguageWrapper\">\r\n");
      out.write("			                    <div class=\" css-container\">\r\n");
      out.write("			                        <span aria-live=\"polite\" aria-atomic=\"false\" aria-relevant=\"additions text\"\r\n");
      out.write("			                            class=\"css-a11yText\">\r\n");
      out.write("			                        </span>\r\n");
      out.write("			                        <div class=\"select__control css-1iewm1a-control skillList_2f\" id=\"first_list\">\r\n");
      out.write("			                            <div class=\"select__value-container select__value-container--is-multi select__value-container--has-value css-1hwfws3 skillSelect_3ff2\">\r\n");
      out.write("												\r\n");
      out.write("										\r\n");
      out.write("			                                <div class=\"css-1g6gooi\">\r\n");
      out.write("			                                    <div class=\"select__input\" style=\"display: inline-block;\">\r\n");
      out.write("			                                        <input autocapitalize=\"none\" autocomplete=\"off\" autocorrect=\"off\"\r\n");
      out.write("			                                            id=\"react-select-2-input\" spellcheck=\"false\" tabindex=\"0\" type=\"text\"\r\n");
      out.write("			                                            aria-autocomplete=\"list\" value=\"\"\r\n");
      out.write("			                                            style=\"box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; outline: 0px; padding: 0px; color: inherit;\">\r\n");
      out.write("			                                        <div\r\n");
      out.write("			                                            style=\"position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 16px; font-family: Arial; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;\">\r\n");
      out.write("			                                        </div>\r\n");
      out.write("			                                    </div>\r\n");
      out.write("			                                </div>\r\n");
      out.write("			                                \r\n");
      out.write("			                            </div>\r\n");
      out.write("			                            <div class=\"select__indicators css-1wy0on6\">\r\n");
      out.write("			                                <div class=\"select__indicator select__clear-indicator css-indicatorContainer\"\r\n");
      out.write("			                                    aria-hidden=\"true\">\r\n");
      out.write("			                                    <label for=\"btnSubmit\"  class=\"css-8mmkcg\" id=\"clear_btn\">\r\n");
      out.write("			                                        <svg height=\"20\" width=\"20\" viewBox=\"0 0 20 20\" aria-hidden=\"true\" focusable=\"false\"\r\n");
      out.write("			                                            class=\"css-8mmkcg\">\r\n");
      out.write("			                                            <path\r\n");
      out.write("			                                                d=\"M14.348 14.849c-0.469 0.469-1.229 0.469-1.697 0l-2.651-3.030-2.651 3.029c-0.469 0.469-1.229 0.469-1.697 0-0.469-0.469-0.469-1.229 0-1.697l2.758-3.15-2.759-3.152c-0.469-0.469-0.469-1.228 0-1.697s1.228-0.469 1.697 0l2.652 3.031 2.651-3.031c0.469-0.469 1.228-0.469 1.697 0s0.469 1.229 0 1.697l-2.758 3.152 2.758 3.15c0.469 0.469 0.469 1.229 0 1.698z\">\r\n");
      out.write("			\r\n");
      out.write("			                                            </path>\r\n");
      out.write("			                                        </svg>\r\n");
      out.write("			                                    </label>    \r\n");
      out.write("			                                </div>\r\n");
      out.write("			                                <span class=\"select__indicator-separator css-indicatorSeparator\"></span>\r\n");
      out.write("			                                <div class=\"select__indicator select__dropdown-indicator css-indicatorContainer\"\r\n");
      out.write("			                                    aria-hidden=\"true\">\r\n");
      out.write("			                                    <label for=\"btnSubmit\"  class=\"css-8mmkcg\" id=\"select_btn\">\r\n");
      out.write("			                                        <svg height=\"20\" width=\"20\" viewBox=\"0 0 20 20\" aria-hidden=\"true\" focusable=\"false\">\r\n");
      out.write("			                                        <path\r\n");
      out.write("			                                        d=\"M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z\">\r\n");
      out.write("			                                        </path>\r\n");
      out.write("			                                        </svg>\r\n");
      out.write("			                                    </label>    \r\n");
      out.write("			                                </div>\r\n");
      out.write("			                            </div>\r\n");
      out.write("			                        </div>\r\n");
      out.write("			                        <div class=\"select_menu css-langage-list select_menu1 list1\">\r\n");
      out.write("			                            <div class=\"\">\r\n");
      out.write("			                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			                                \r\n");
      out.write("			                            </div>\r\n");
      out.write("			                        </div>\r\n");
      out.write("			                        <div><input name=\"likeLanguages\" type=\"hidden\" value=\"java\"></div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <div class=\"datepicker_dateWrapper__3XHYP\">\r\n");
      out.write("                            <div class=\"datepicker_datepickerWrapper__aUl1_\">\r\n");
      out.write("                                <!-- 시작 예정일  -->\r\n");
      out.write("                                <div class=\"datepicker_labelText__3Swb3\">시작 예정일</div>\r\n");
      out.write("                                <div class=\"MuiFormControl-root MuiTextField-root css-feqhe6\">\r\n");
      out.write("                                    <div\r\n");
      out.write("                                        class=\"MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-adornedEnd css-1bn53lx\">\r\n");
      out.write("                                        <!-- 시작 예정일 안 달력 바  -->\r\n");
      out.write("                                        <input aria-invalid=\"false\" placeholder=\"yyyy-mm-dd\" type=\"date\"\r\n");
      out.write("                                            class=\"MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-1uvydh2\"\r\n");
      out.write("                                            value=\"\" id=\"mui-1\" style=\"font-size: 18px;\" name=\"boardStartDate\">\r\n");
      out.write("                                        <fieldset aria-hidden=\"true\" class=\"MuiOutlinedInput-notchedOutline css-igs3ac\">\r\n");
      out.write("                                            <legend class=\"css-hdw1oc\" style=\"display: none;\">\r\n");
      out.write("                                                <span class=\"notranslate\">​</span>\r\n");
      out.write("                                            </legend>\r\n");
      out.write("                                        </fieldset>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 연락 방법 -->\r\n");
      out.write("                <ul class=\"postinfo_inputList__3SKF-\">\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <label class=\"selectbox_labelText__3Q9iz\" for=\"onoffline\">연락 방법</label>\r\n");
      out.write("                        <div class=\"postinfo_contactInput__3nnsb\" style=\"margin:0 auto;\">\r\n");
      out.write("                            <input class=\"input_customInput__1e1Il\" id=\"input0\" style=\"pointer-events: none;\" value=\"카카오톡 오픈채팅\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"postinfo_contactInput__3nnsb\">\r\n");
      out.write("                            <input class=\"input_customInput__1e1Il\" id=\"input1\" placeholder=\"링크를 입력해주세요\" value=\"\" name=\"boardContact\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"postinfo_listItem__OFhXr\">\r\n");
      out.write("                        <label class=\"selectbox_labelText__3Q9iz\" for=\"onoffline\">회사명</label>\r\n");
      out.write("                        <div class=\" css-2b097c-container css_newT6\">\r\n");
      out.write("                            <span aria-live=\"polite\" aria-atomic=\"false\" aria-relevant=\"additions text\"\r\n");
      out.write("                                class=\"css-7pg0cj-a11yText\"></span>\r\n");
      out.write("                            <div class=\"select__control css-1iewm1a-control\">\r\n");
      out.write("                                <div class=\"select__value-container select__value-container--has-value css-1hwfws3\">\r\n");
      out.write("                                    <div name=\"Company\" class=\"select__single-value css-1uccc91-singleValue\">회사 선택</div>\r\n");
      out.write("                                    <div class=\"css-1g6gooi\">\r\n");
      out.write("                                        <div class=\"select__input\" style=\"display: inline-block;\">\r\n");
      out.write("                                            <input autocapitalize=\"none\" autocomplete=\"off\" autocorrect=\"off\"\r\n");
      out.write("                                                id=\"react-select-7-input\" spellcheck=\"false\" tabindex=\"0\" type=\"text\"\r\n");
      out.write("                                                aria-autocomplete=\"list\" value=\"\"\r\n");
      out.write("                                                style=\"box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; outline: 0px; padding: 0px; color: inherit;\">\r\n");
      out.write("                                            <div\r\n");
      out.write("                                                style=\"position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 16px; font-family: Arial; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"select__indicators css-1wy0on6\">\r\n");
      out.write("                                    <span class=\"select__indicator-separator css-1okebmr-indicatorSeparator\"></span>\r\n");
      out.write("                                    <div class=\"select__indicator select__dropdown-indicator css-tlfecz-indicatorContainer\"\r\n");
      out.write("                                        aria-hidden=\"true\">\r\n");
      out.write("                                        <svg height=\"20\" width=\"20\" viewBox=\"0 0 20 20\" aria-hidden=\"true\"\r\n");
      out.write("                                            focusable=\"false\" class=\"css-8mmkcg\">\r\n");
      out.write("                                            <path\r\n");
      out.write("                                                d=\"M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z\">\r\n");
      out.write("\r\n");
      out.write("                                            </path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 연락방법 누르면 더 보기 DIV  -->\r\n");
      out.write("                            <div class=\"select__menu css-26l3qy-menu newInAction\">\r\n");
      out.write("                                <div class=\"select__menu-list css-11unzgr\">\r\n");
      out.write("                                   \r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <input style=\"display:none !important;\" name=\"boardCompany\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"postinfo_contactInput__3nnsb\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <!-- 2번 프로젝트에 대해 설명 해주세여  -->\r\n");
      out.write("            <section>\r\n");
      out.write("                <div class=\"postRegister_postContentWrapper__3BXZ6\">\r\n");
      out.write("                    <span class=\"postRegister_sequence__nC1Px\">2</span>\r\n");
      out.write("                    <h2 class=\"postRegister_text__17jg3\">프로젝트에 대해 소개해주세요.</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <section>\r\n");
      out.write("                    <label class=\"input_labelText__3R2TI\" for=\"input\">제목</label> \r\n");
      out.write("                    <input class=\"input_customInput__1e1Il\" id=\"input\" placeholder=\"글 제목을 입력해주세요!\" value=\"\" name=\"boardTitle\">\r\n");
      out.write("                        <textarea id=\"summernote\" placeholder=\"\" name=\"boardContent\"> </textarea>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"writebutton_buttons__2qW83\">\r\n");
      out.write("                        <!-- <button type=\"button\" class=\"writebutton_cancelButton__2W7b_\">취소</button> -->\r\n");
      out.write("                        <!-- <button type=\"button\" class=\"writebutton_registerButton__n_O2M\" onclick=\"send()\">글 등록</button> -->\r\n");
      out.write("                        \r\n");
      out.write("                        <input type=\"button\" class=\"writebutton_cancelButton__2W7b_\" style=\"width:50px; height:35px;\" value=\"취소\" onclick=\"\"/>\r\n");
      out.write("                        <input type=\"button\" class=\"writebutton_registerButton__n_O2M\" style=\"width:70px; height:35px;\" value=\"글 등록\" onclick=\"send()\"/>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </section>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/board/newPage.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	let dateElement = document.getElementById('mui-1');\r\n");
      out.write("	let date = new Date().toISOString().substring(0, 10);\r\n");
      out.write("	\r\n");
      out.write("	function send(){\r\n");
      out.write("	  	if(!newPage.boardTitle.value){\r\n");
      out.write("	       alert(\"제목을 작성해주세요.\");\r\n");
      out.write("	       return;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(!newPage.boardContent.value){\r\n");
      out.write("	       alert(\"내용을 작성해주세요.\");\r\n");
      out.write("	       return;\r\n");
      out.write("	    }\r\n");
      out.write("	    if(!newPage.boardContact.value){\r\n");
      out.write("	       alert(\"연락 방법(링크)을 작성해주세요.\");\r\n");
      out.write("	       return;\r\n");
      out.write("	    }\r\n");
      out.write("	    if(!newPage.boardRecruitNumber.value){\r\n");
      out.write("	    	alert(\"모집 인원을 입력해주세요.\");\r\n");
      out.write("		    return;\r\n");
      out.write("	    }else if(newPage.boardRecruitNumber.value > 100){\r\n");
      out.write("	    	alert(\"모집 인원은 최대 100명까지 입력할 수 있습니다.\");\r\n");
      out.write("	    	return;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(dateElement.value < date) {\r\n");
      out.write("	        alert('시작 예정일은 지난 날짜로 선택 할 수 없습니다.');\r\n");
      out.write("	        dateElement.value = date;\r\n");
      out.write("	        return;\r\n");
      out.write("	    }\r\n");
      out.write("	    var boardCategory= document.getElementsByName('Category');\r\n");
      out.write("	    var boardWay= document.getElementsByName('Way');\r\n");
      out.write("	    var boardPeriod= document.getElementsByName('Period');\r\n");
      out.write("	    var boardCompany= document.getElementsByName('Company');\r\n");
      out.write("	\r\n");
      out.write("	    newPage.boardCategory.value = boardCategory[0].innerText;\r\n");
      out.write("	    newPage.boardWay.value = boardWay[0].innerText;\r\n");
      out.write("	    newPage.boardPeriod.value = boardPeriod[0].innerText;\r\n");
      out.write("	    newPage.boardCompany.value = boardCompany[0].innerHTML;\r\n");
      out.write("	\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    if(newPage.boardCategory.value ==\"스터디/프로젝트\"){\r\n");
      out.write("	    	alert(\"모집 구분을 선택해주세요.\");\r\n");
      out.write("		    return;\r\n");
      out.write("	    }\r\n");
      out.write("	    if(newPage.boardWay.value ==\"온라인/오프라인\"){\r\n");
      out.write("	    	alert(\"진행 방식을 선택해주세요.\");\r\n");
      out.write("		    return;\r\n");
      out.write("	    }\r\n");
      out.write("	    if(newPage.boardPeriod.value ==\"기간 미정~6개월 이상\"){\r\n");
      out.write("	    	alert(\"진행 기간을 선택해주세요.\");\r\n");
      out.write("		    return;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(newPage.boardCompany.value ==\"회사 선택\"){\r\n");
      out.write("	    	alert(\"회사를 선택해주세요.\");\r\n");
      out.write("		    return;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	\r\n");
      out.write("	    newPage.submit();\r\n");
      out.write("	 }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /app/board/newPage.jsp(274,31) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("skill");
      // /app/board/newPage.jsp(274,31) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${skills}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			                                <div class=\"select_option css-list-option skillTotalList\" id=\"\" tabindex=\"-1\">");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</div>\r\n");
            out.write("			                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /app/board/newPage.jsp(275,113) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${skill.getSkillName()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /app/board/newPage.jsp(364,37) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boards != null and fn:length(boards) > 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    		");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                    	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /app/board/newPage.jsp(365,38) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("board");
      // /app/board/newPage.jsp(365,38) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boards}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    				<div class=\"select__option css-yt9ioa-option\" id=\"react-select-3-option-1\" tabindex=\"-1\">");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</div>\r\n");
            out.write("                                    		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /app/board/newPage.jsp(366,129) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.getCompanyName()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
